### ISSUE TITLE
line 136, in accum  vals[indx].append(val) AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ISSUE THREAD

**Issue by evgenykam** [scipy/scipy-cookbook#12]
Hi,
I'm trying to run your function on Pyhton3.4, but getting the following error:

File "./demo_non_local_dehazing.py", line 136, in accum
    vals[indx].append(val)
AttributeError: 'numpy.ndarray' object has no attribute 'append'

How can I solve this issue?

Thank you in advance!
Evgeny

**Comment by pv** [comment]
This is user-contributed content, and the authors of the pages do not 
follow this issue tracker. As explained in the text box where you wrote 
your message:
.
Note that the cookbook is uncurated user-contributed content: for errors 
or typos etc. in the notebooks, please send pull requests fixing them 
rather than reporting them.
