### ISSUE TITLE
Discussion 

### ISSUE THREAD

**Issue by AdrianKriger** [scipy/scipy-cookbook#57]
Thank you for this work. It’s pretty amazing.

Please open a discussion.

**Comment by ilayn** [comment]
Hi @AdrianKriger we are using GitHub strictly for bugs and similar code related issues. Discussions are not suitable for us since we don't want to have "how to do x, y, z?" questions here. We have a SciPy dev/user mailing list and you can use all social platforms like Stackoverflow, reddit, and various discourse websites for usage questions.
